bincom_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('elections.urls', namespace='elections')),
]

elections/urls.py
from django.urls import path, include

from . import views

app_name = 'elections'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('results/', include('results.urls', namespace='results')),
]

results/urls.py
from django.urls import path

from . import views

app_name = 'results'

urlpatterns = [
    path('polling-unit/', views.polling_unit_results_view, name='polling_unit_results'),
    path('fetch-next-division/', views.fetch_next_division_by_previous_division_view, name='fetch_next_division'),
    path('lga/', views.lga_results_view, name='lga_results'),
    path('new/', views.store_party_results_view, name='store_party_results')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, inihetial-scale=1.0">
    <title>Bincom Test | {% block title %}{% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'styles/base.css' %}">
    {% block styles %}
    {% endblock styles %}
</head>
<body>
    <header>
        <nav class="container">
            <div id="logo">
                <a href="{% url 'elections:index' %}">Bincom Test</a>
            </div>

            <div id="nav-links">
                <ul>
                    <li><a href="{% url 'elections:results:polling_unit_results' %}">Polling Unit Results</a></li>
                    <li><a href="{% url 'elections:results:lga_results' %}">LGA Results</a></li>
                    <li><a href="{% url 'elections:results:store_party_results' %}">Add Party Result</a></li>
                </ul>
            </div>

            <div id="dropdown-btn">
                <div id="bar1"></div>
                <div id="bar2"></div>
            </div>
        </nav>

        <div id="dropdown-nav">
            <ul>
                <li><a href="{% url 'elections:results:polling_unit_results' %}">Polling Unit Results</a></li>
                <li><a href="{% url 'elections:results:lga_results' %}">LGA Results</a></li>
                <li><a href="{% url 'elections:results:store_party_results' %}">Add Party Result</a></li>
            </ul>
        </div>
    </header>

    {% block content %}
    {% endblock content %}
</body>

<script src="{% static 'scripts/base.js' %}"></script>
{% block scripts %}
{% endblock scripts %}

</html>